FROM maven:latest
WORKDIR /code
COPY . /code
RUN mvn clean install -DskipTests=true
EXPOSE 8080
ARG DB_HOST
ENV DB_HOST ${DB_HOST}
ARG DB_USERNAME
ENV DB_USERNAME ${DB_USERNAME}
ARG DB_PASSWORD
ENV DB_PASSWORD ${DB_PASSWORD}
ARG DB_NAME
ENV DB_NAME ${DB_NAME}
ARG JWT_SECRET
ENV JWT_SECRET ${JWT_SECRET}
ARG TEST_VALID_EMAIL_API
ENV TEST_VALID_EMAIL_API ${TEST_VALID_EMAIL_API}
ARG TEST_VALID_USER_PASSWORD_API
ENV TEST_VALID_USER_PASSWORD_API ${TEST_VALID_USER_PASSWORD_API}

CMD ["java","-jar", "/code/target/IWantItDataWay-API-1.0-SNAPSHOT.jar", "server", "/code/config.yml"]