USE IWantItDataWay_StephenH;

AlTER TABLE job_role
ADD job_role_responsibility TEXT;

INSERT INTO job_role (job_role_responsibility)
VALUES
	('As a Workday Consultant in Kainos, you’ll be a lead consultant in implementing and configuring Workday solutions for our global customer base and an expert in your chosen Workday specialist capability or capabilities – such as Recruitment, Compensation/Advanced Comp, Payroll/Time Tracking/Absence, etc.'),
    ('As a Senior Test Engineer (Senior Associate) in Kainos, you’ll work within a multi- skilled agile team, developing and executing functional automated and manual tests to help the team deliver working application software that meets user needs. You’ll do this whilst learning about new technologies and approaches, with talented colleagues who will help you learn, develop and grow.'),
    ('As a Senior Software Engineer (Senior Associate) in Kainos, you’ll be responsible for developing high quality solutions which delight our customers and impact the lives of users worldwide. It’s a fast-paced environment so it is important for you to make sound, reasoned decisions. You’ll do this whilst learning about new technologies and approaches, with talented colleagues that will help you to learn, develop and grow as you, in turn, mentor those around you.'),
    ('As a Dynamics 365 Solution Architect at Kainos you will manage the architecture on product- based projects, analyse the gap between product offering and customer needs, design technical solutions with the right blend of configuration, customisation, integration and bespoke development needed to deliver a working end to end system. You’ll manage multi-skilled agile teams to combine configuration and custom development to deliver high quality solutions. You’ll work with customer architects to agree functional and non- functional designs, advising customers and managers on the estimated effort, technical implications and complexity.'),
    ('As a Senior Test Engineer (Senior Associate) in Kainos, you’ll work within a multi- skilled agile team, developing and executing functional automated and manual tests to help the team deliver working application software that meets user needs. You’ll do this whilst learning about new technologies and approaches, with talented colleagues who will help you learn, develop and grow.'),
    ('As a Graduate Software Engineer with Kainos, you will work on projects where you can make a real difference to people’s lives – the lives of people you know. After taking part in our award-winning, seven-week Engineering Academy, you will then join one of our many project teams, to learn from our experienced developers, project managers and customer-facing staff. You’ll have great support and mentoring, balanced with the experience of being given real, meaningful work to do, to help you truly develop both technically and professionally.   '),
    ('As a Lead Workday Consultant in Kainos, you’ll be a lead consultant in implementing and configuring Workday solutions for our global customer base and an expert in your chosen Workday specialist capability or capabilities. As an expert in a team of consultants, you will manage relationships with our customers, and shape and deliver solutions that are aligned to customer needs, fit for purpose and commercially viable. You’ll provide excellent consulting and guidance to customers, truly understanding their business.'),
    ('Here at Kainos we have an exciting opportunity for a Senior Test Manager to join our team. You will own the development and execution of the test strategy, test planning, test case scenario creation, test resource coordination and successfully guide and manage test execution to ensure a successful outcome for our clients. The individual will have proven experience on complex Your Way implementations where they have provided coordination and support to Project Management to ensure that all aspects of the project are completed on time and in alignment with project schedule.'),
    ('As a Graduate Test/ QA Engineer in Kainos, after taking part in our award-winning, seven-week Engineering Academy you’ll work within a multi-skilled agile team, developing and executing functional automated and manual tests to help the team deliver working application software that meets user needs. You’ll do this whilst learning about new technologies and approaches, with talented colleagues who will help you learn, develop and grow.'),
    ('As a Workday AMS Consultant in Kainos, you’ll be a lead consultant in implementing and configuring Workday solutions for our global customer base and an expert in your chosen Workday specialist capability or capabilities – such as Recruitment, Compensation/Advanced Comp, Payroll/Time Tracking/Absence, etc.');
